USE ROLE ACCOUNTADMIN;
CREATE WAREHOUSE IF NOT EXISTS ZOMATO_WH
    WAREHOUSE_SIZE = 'XSMALL'
    AUTO_SUSPEND = 70
    AUTO_RESUME = TRUE
    INITIALLY_SUSPENDED = TRUE;

-- Database + medallion schema.

CREATE DATABASE IF NOT EXISTS ZOMATO;
CREATE SCHEMA IF NOT EXISTS ZOMATO.RAW;
CREATE SCHEMA IF NOT EXISTS ZOMATO.STAGING;
CREATE SCHEMA IF NOT EXISTS ZOMATO.MART;
CREATE SCHEMA IF NOT EXISTS ZOMATO.SNAPSHOPTS;
CREATE SCHEMA IF NOT EXISTS ZOMATO.AI;

-- ROLE dbt/airflow will use

CREATE ROLE IF NOT EXISTS DBT_ROLE;
GRANT USAGE ON WAREHOUSE ZOMATO_WH TO ROLE DBT_ROLE;
GRANT OPERATE ON WAREHOUSE ZOMATO_WH TO ROLE DBT_ROLE;
GRANT ALL ON DATABASE ZOMATO TO ROLE DBT_ROLE;
GRANT ALL ON ALL SCHEMAS IN DATABASE ZOMATO TO ROLE DBT_ROLE;
GRANT ALL ON FUTURE SCHEMAS IN DATABASE ZOMATO TO ROLE DBT_ROLE;
GRANT ALL ON FUTURE TABLES IN DATABASE ZOMATO TO ROLE DBT_ROLE;
GRANT ALL ON FUTURE VIEWS IN DATABASE ZOMATO TO ROLE DBT_ROLE;


-- 
set my_user = current_user();
GRANT ROLE DBT_ROLE TO USER IDENTIFIER($my_user);

grant role dbt_role to role accountadmin;

select 'Setup Complited' As status;

