USE DATABASE ZOMATO;
USE SCHEMA RAW;



CREATE OR REPLACE STORAGE INTEGRATION ZOMATO_S3_INT
    TYPE = EXTERNAL_STAGE
    STORAGE_PROVIDER = 'S3'
    ENABLED = TRUE
    STORAGE_AWS_ROLE_ARN = '<Your S3 Role name>'
    STORAGE_ALLOWED_LOCATIONS = ('s3://<Your S3 Bucket name>')

DESC INTEGRATION ZOMATO_S3_INT

GRANT USAGE ON INTEGRATION ZOMATO_S3_INT TO ROLE DBT_ROLE;

