--STORAGE_AWS_IM_USER_ARN = arn:aws:iam::261414899064:user/s5b12000-s
--STORAGE_AWS_EXTERNAL_ID = BH84454_SFCRole=3_zEQEgiFL3P5iTK6iSw9DYuDr9Ws=




CREATE OR REPLACE FILE FORMAT ZOMATO.RAW.CSV_FMT
    TYPE = "CSV"
    COMPRESSION = "AUTO"
    FIELD_DELIMITER = ","
    SKIP_HEADER = 1
    FIELD_OPTIONALLY_ENCLOSED_BY = '"'
    EMPTY_FIELD_AS_NULL = TRUE
    NULL_IF = (' ', '\\N', 'NULL')
    TRIM_SPACE = FALSE
    ERROR_ON_COLUMN_COUNT_MISMATCH = FALSE;


CREATE OR REPLACE STAGE ZOMATO.RAW.ZOMATO_RAW_STAGE
    STORAGE_INTEGRATION = ZOMATO_S3_INT
    URL = 's3://zomato-data-priyeshaws/raw'
    FILE_FORMAT = (FORMAT_NAME = CSV_FMT)

LIST @ZOMATO_RAW_STAGE;

